config/routes.rb
Rails.application.routes.draw do
  mount AppStock::Base => '/' # route API
  root to: 'books#index'
  resources :books do
    resources :flows
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId
  friendly_id :isbn, use: :slugged

  has_many :flows

end

app/models/flow.rb
class Flow < ApplicationRecord
  belongs_to :book

  validates :newQuantity, presence: :true, allow_blank: :false
  validates :oldQuantity, presence: :true, allow_blank: :false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books

  acts_as_token_authenticatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show]
  before_action :book_flows, only: [:show]

  def index
    @books = Book.all
  end

  def show
    @flow = Flow.new
    # add default value to new_flow form to previous_stock field
    @previous_quantity = @flows.empty? ? '0' : @flows.last.newQuantity
  end

  private

  def book_params
    params.require(:book).permit(:isbn, :title, :quantity)
  end

  def set_book
    # friendly_id to find book by Isbn instead Id (let's check out book.rb)
    @book = Book.friendly.find(params[:id])
  end

  def book_flows
    @flows = @book.flows
  end
end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController
  before_action :set_book, only: [:index]

  def create
    @book = Book.friendly.find(params[:book_id])
    @flow = Flow.new(flow_params)
    @flow = @book.flows.build(flow_params)
    @flow.book = @book
    if @flow.save
      # update book quantity when flow is saving.
      @book.update(quantity: @flow.newQuantity)
      respond_to do |format|
        format.html { redirect_to book_path(@book) }
        format.js {}
      end
    else
      respond_to do |format|
        format.html { render 'flows/show' }
        format.js {}
      end
    end
  end

  private

  def set_book
    # friendly_id to find book by Isbn instead Id (let's check out book.rb)
    @book = Book.friendly.find(params[:id])
  end

  def flow_params
    params.require(:flow).permit(:oldQuantity, :newQuantity, :comment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/views/books/index.html.erb
<h3 class="text-center">Books</h3>

<div class="index-wrapper">
  <div class="tab-content">
    <table class="fixed_headers">
      <thead>
        <tr>
          <th>Isbn</th>
          <th>Book</th>
          <th>Current Stock</th>
        </tr>
      </thead>
      <% @books.each do |book|%>
      <tbody>
        <tr>
          <td> <%= link_to book_path(book) do %>
            <%= book.isbn%></td>
            <%end%>
          <td><%= book.title%></td>
          <td><%= book.flows.last.newQuantity.nil? ? 0 : book.flows.last.newQuantity %></td>
        </tr>
      </tbody>
      <%end%>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<h3 class="text-center"><%= @book.title%></h3>
<%= link_to books_path do%>
  <i class="fa fa-arrow-left fa-3x" aria-hidden="true"></i>
<%end%>
<div class="book-info">
  <div class="isbn-wrapper text-center">
    <p>ISBN</p>
    <p class="isbn"><%= @book.isbn%></p>
  </div>
  <div id="currentStock">
      <%= render "flows/stock"%>
  </div>
</div>

<div class="index-wrapper"  >
  <table class="fixed_headers" id="flows">
    <thead>
      <tr>
        <th>Updated at</th>
        <th>Previous Stock</th>
        <th>New Stock</th>
        <th>Comment</th>
      </tr>
    </thead>
    <% @flows.each do |flow|%>
      <%= render "flows/show", flow: flow%>
    <%end%>
  </table>
</div>

<div class="form-wrapper">
  <%= render "flows/new", book: @book, flow: @flow%>
</div>

app/views/flows/_new.html.erb
<div class="form-content text-center">
  <%= simple_form_for([@book, @flow], remote: true) do |f| %>
    <div class="input-form-flow">
      <%= f.input :oldQuantity, label: "Previous stock", input_html: {value: f.object.oldQuantity ||  @previous_quantity.nil? ? 0 : @previous_quantity } %>
      <%= f.input :newQuantity, label: "New stock"%>
      <%= f.input :comment, label: "Comment", :input_html => {maxlength: 45} %>
    </div>
    <%= f.submit "Update stock", class: "calltoaction-form" %>
  <% end %>
</div>

app/views/flows/_show.html.erb
  <tbody>
    <tr>
      <td><%= flow.created_at.strftime('%m-%e-%y %H:%M') %></td>
      <td><%= flow.oldQuantity.nil? ? 0 : flow.oldQuantity%></td>
      <td><%= flow.newQuantity.nil? ? 0 : flow.newQuantity%></td>
      <td><%= flow.comment.nil? ? '-' : flow.comment%></td>
    </tr>
  </tbody>

app/views/flows/_stock.html.erb
<div class="counter text-center">
  <p>Stock</p>
  <%if @flow.newQuantity.nil? %>
    <div class="start-counter">
      <td ><%= @book.flows.last.newQuantity.nil? ? 0 : @book.flows.last.newQuantity  %></td>
    </div>
  <%else%>
    <div class="current-counter">
      <td><%= @flow.newQuantity.nil? ? 0 : @flow.newQuantity%></td>
    </div>
  <%end%>
</div>

app/views/flows/create.js.erb
$('#flows').append('<%= j render 'flows/show', flow: @flow %>');
$('#currentStock').append('<%= j render 'flows/stock', flow: @flow %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>